add space to not confuse gcc's C++0x extensions
- since be5a3cf, gave compiler error
    nlpi_ipopt.cpp:1987:11: error: unable to find string literal
    operator ‘operator"" IPOPT_VERSION’
  with some gcc versions